version: '3.4'

services:
  mch.api:
    image: ${DOCKER_REGISTRY-}mchapi
    build:
      context: .
      dockerfile: MCH.API/Dockerfile
    ports:
      - 5000:80
      
  mch.parser:
     image: ${DOCKER_REGISTRY-}mchaparser
    build:
      context: .
      dockerfile: MCH.PARSER/Dockerfile
    

  nginx:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 4201:80
     
 